// modules/counter/client-react/index.tsx
import React from 'react';
import { Route } from 'react-router-dom';

import ClientModule from '@gqlapp/module-client-react';
import Counter from './containers/Counter';
import counters from './counters';
import resources from './locales';

export default new ClientModule(counters, {
  route: [<Route exact path={__TEST__ ? '/counter' : '/'} component={Counter} />],
  localization: [{ ns: 'counter', resources }]
});

// modules/counter/client-angular/index.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import ClientModule from '@gqlapp/module-client-angular';
import counters from './counters';
import { CounterComponent } from './containers/Counter';

@NgModule({
  imports: [CommonModule, ...counters.counterModule],
  declarations: [CounterComponent],
  exports: [...counters.counterModule]
})
export class CounterModule {}

export default new ClientModule(counters, {
  route: [{ path: '', component: CounterComponent, data: { title: 'Counter', meta: 'Counter example page' } }],
  module: [CounterModule]
});
